# Generated by Django 5.1.2 on 2024-11-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Evento_proy.evento')),
                ('artista', models.CharField(max_length=200)),
                ('duracion', models.CharField(max_length=50)),
            ],
            bases=('Evento_proy.evento',),
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Evento_proy.evento')),
                ('tema', models.CharField(max_length=200)),
                ('orador', models.CharField(max_length=200)),
            ],
            bases=('Evento_proy.evento',),
        ),
    ]
